#!/bin/sh -u
exec 2>&1
LOGDIR=/var/log/qnlog
while [ ! -f /var/tmp/.first_init ]; do
        sleep 1
done
test -d "$LOGDIR" || mkdir "$LOGDIR"
# Retention policy setting - rotate on 50 KB max size, keep 1x old logs
cat > "$LOGDIR"/config <<EOF
s50000
n1
EOF
exec svlogd -tt "$LOGDIR"
